### ISSUE TITLE
Holdings screen: Total Change % sorting might be incorrect due to forex and purchase exchange rate overrides

### ISSUE THREAD

**Issue by mikezliu** [mystocksportfolio/issues#225]
Possibly because sorting will sort on the total change % and not on the total change % local column

Affected columns:
Daily change
Daily change %
Total change
Total change %

Absolute, Ascending

**Comment by Geert1964** [comment]
Hello!
I reported this (ennoying) bug already a while ago.
I'm happy this will be addressed.

**Comment by mikezliu** [comment]
This will be fixed for the 'holdings' screen in Android 2.910 release. For overview screen it is harder to fix and there is a separate issue to track that: https://github.com/mystocksportfolio/issues/issues/227

**Comment by Geert1964** [comment]
Thank you Mike for finally solving this bug. I look forward to the new release on Android.
I made a little donation to thank you.
The sorting for the overview screen is not so important to me, as I sort the portfolios in this overview manually.

**Comment by mikezliu** [comment]
We ran into a bug during testing; we halted the release and we're preparing to release a new version (2.912) with a fix

**Comment by Geert1964** [comment]
Hello Mike.
I downloaded yesterday this new version 2.912.
It did what was promised!
Thank you very much!
I waited so long for this fix to come.
Best regards,
Geert
