### ISSUE TITLE
Title not changed when pressing back-to-last-page HW keymap (Android)

### ISSUE THREAD

**Issue by Nowar** [mystocksportfolio/issues#353]
Samsung has a simple gesture to map to HW key map as back-to-last-page.
When I in some portfolio inside (eg: portfolio "Day"), then do this action.
I'm back to overview page correctly, but the title is still portfolio name (i.e., Day)
Demo: Fig 1. to Fig 2.
Please help since it's kind of confusing. Thanks!

Fig 1.
![Screenshot_20230815_170026_My Stocks Portfolio](https://github.com/mystocksportfolio/issues/assets/546250/a5e36ada-d0c5-4810-8639-82b958f7defb)

Fig 2.
![Screenshot_20230815_170039_My Stocks Portfolio](https://github.com/mystocksportfolio/issues/assets/546250/411b2027-e0b5-4485-8e73-2468fa9002c2)

**Comment by mikezliu** [comment]
Ok I see the issue, it will be fixed in the next release

**Comment by mikezliu** [comment]
https://github.com/mystocksportfolio/issues/issues/354
