### ISSUE TITLE
No widget on ios18

### ISSUE THREAD

**Issue by Leletp80** [mystocksportfolio/issues#382]
Since I updated my iphone to iOS 18 widget is not visible anymore.

**Comment by mikezliu** [comment]
Today extension widgets have been removed on iOS 18 by Apple: https://forums.developer.apple.com/forums/thread/650350#:~:text=Today%20Extensions%20continue%20to%20be,Link%20or%20the%20widgetURL%20modifier.

We are working on new WidgetKit based widgets for iOS 18 and above: https://developer.apple.com/documentation/widgetkit/

**Comment by mikezliu** [comment]
Closing as dupe of https://github.com/mystocksportfolio/issues/issues/192
