### ISSUE TITLE
Export PDF report shows holdings in excluded portfolios

### ISSUE THREAD

**Issue by mikezliu** [mystocksportfolio/issues#48]

**Comment by mikezliu** [comment]
Took a look and the code is excluding excluded portfolios. Closing as not repro. Asked customer for more information.

**Comment by jab81** [comment]
If an included and excluded portfolio contain the same stock, the stock shares from the excluded portfolio are included in the PDF report.

**Comment by mikezliu** [comment]
Need to investigate

**Comment by mikezliu** [comment]
Got a repro - it looks like it happens for duplicate symbol names. Working on a fix
